use std::path::Path;

use crate::luac::LuaCompiler;
use crate::manifest::{ContentItem, Manifest};
use crate::packages::path::PackagePath;
use crate::radio;

use super::PackageError;
use super::transfer::{build_exclude, copy_content_items, count_files, count_lua_files};

/// Layout of a built package.
pub enum BuildLayout {
    /// `edgetx.yml` at the root with content at each item's `path`, ready for
    /// `pkg install ./<dir>`.
    Package,
    /// Content at each item's install destination and no manifest, so the tree
    /// extracts straight onto the SD card root.
    SdOverlay,
}

pub struct BuildOptions<'a> {
    pub manifest: &'a Manifest,
    pub manifest_dir: &'a Path,
    pub out_dir: &'a Path,
    pub include_dev: bool,
    pub layout: BuildLayout,
}

#[derive(Debug)]
pub struct BuildResult {
    /// The manifest written to the output directory. `None` for [`BuildLayout::SdOverlay`].
    pub manifest: Option<Manifest>,
    pub files_copied: usize,
    pub scripts_compiled: usize,
}

/// Copy a package into `out_dir` and compile a `.luac` next to every `.lua`.
///
/// Both the sources and the generated bytecode land in the output, because the
/// radio only discovers some script types (widgets in particular) by their `.lua`.
/// Everything happens on local disk: SD cards are far too slow to compile against.
pub fn build_package(
    opts: &BuildOptions,
    compiler: &mut dyn LuaCompiler,
    on_copy: &mut dyn FnMut(&str),
    on_compile: &mut dyn FnMut(&str),
) -> Result<BuildResult, PackageError> {
    let staged = match opts.layout {
        BuildLayout::SdOverlay => {
            copy_content_items(
                opts.manifest,
                opts.manifest_dir,
                opts.out_dir,
                opts.include_dev,
                on_copy,
            )?
            .1
        }
        BuildLayout::Package => stage_sources(opts, on_copy)?,
    };

    let scripts_compiled = compile_staged(opts.out_dir, &staged, compiler, on_compile)?;

    let manifest = match opts.layout {
        BuildLayout::SdOverlay => None,
        BuildLayout::Package => {
            let m = built_manifest(opts);
            write_manifest(&m, opts.out_dir)?;
            Some(m)
        }
    };

    Ok(BuildResult {
        manifest,
        files_copied: staged.len(),
        scripts_compiled,
    })
}

/// Copy content to `out_dir` at each item's own `path`, so the emitted manifest
/// resolves against the output root and `dest` still applies at install time.
fn stage_sources(
    opts: &BuildOptions,
    on_copy: &mut dyn FnMut(&str),
) -> Result<Vec<PackagePath>, PackageError> {
    let mut staged = Vec::new();

    for item in opts.manifest.content_items(opts.include_dev) {
        let source_root = opts
            .manifest
            .resolve_content_path(opts.manifest_dir, &item.path)
            .map_err(|e| PackageError::ContentResolve {
                path: item.path.clone(),
                source: e,
            })?;

        let exclude = build_exclude(opts.manifest.package.binary, &item);
        let copy_opts = radio::copy::CopyOptions {
            dry_run: false,
            exclude: &exclude,
        };

        let mut on = |dest: &Path| {
            if let Ok(rel) = dest.strip_prefix(opts.out_dir) {
                staged.push(PackagePath::new(rel.to_string_lossy()));
            }
            on_copy(&dest.display().to_string());
        };

        radio::copy::copy_paths(
            &source_root,
            opts.out_dir,
            &[radio::copy::CopyPath::same(item.path.as_str())],
            &copy_opts,
            &mut on,
        )?;
    }

    Ok(staged)
}

/// Compile every staged `.lua`, writing the bytecode beside it.
fn compile_staged(
    out_dir: &Path,
    staged: &[PackagePath],
    compiler: &mut dyn LuaCompiler,
    on_compile: &mut dyn FnMut(&str),
) -> Result<usize, PackageError> {
    let mut compiled = 0;

    for rel in staged {
        let Some(compiled_rel) = rel.compiled_path() else {
            continue;
        };

        let dest = out_dir.join(compiled_rel.as_str());
        if dest.exists() {
            log::info!("{compiled_rel} ships with the package, not recompiling");
            continue;
        }

        let src = out_dir.join(rel.as_str());
        let source = std::fs::read(&src).map_err(|e| PackageError::Io {
            context: format!("reading {}", src.display()),
            source: e,
        })?;

        on_compile(rel.as_str());

        let bytecode = compiler
            .compile(&source)
            .map_err(|e| PackageError::Compile {
                path: rel.to_string(),
                source: e,
            })?;

        std::fs::write(&dest, &bytecode).map_err(|e| PackageError::Io {
            context: format!("writing {}", dest.display()),
            source: e,
        })?;

        copy_mtime(&src, &dest);
        compiled += 1;
    }

    Ok(compiled)
}

/// Give the bytecode its source's timestamp, as the radio does when it compiles a
/// script itself. The radio loads whichever of the two is newer and prefers the
/// bytecode on a tie, so matching timestamps stop it from recompiling.
pub(crate) fn copy_mtime(src: &Path, dest: &Path) {
    let result = std::fs::metadata(src)
        .and_then(|m| m.modified())
        .and_then(|t| {
            std::fs::File::options()
                .write(true)
                .open(dest)
                .and_then(|f| f.set_modified(t))
        });

    if let Err(e) = result {
        log::warn!("could not set the timestamp on {}: {e}", dest.display());
    }
}

/// Rewrite the manifest to describe the built tree rather than the source tree.
fn built_manifest(opts: &BuildOptions) -> Manifest {
    let mut m = opts.manifest.clone();

    // Content now sits at the output root, and neither screenshots nor variant
    // manifests are part of a build.
    m.package.source_dir = Default::default();
    m.package.screenshots.clear();
    m.package.variants.clear();
    // Bytecode ships with the package, so `.luac` must survive the install copy.
    m.package.binary = true;

    let include_dev = opts.include_dev;
    let out_dir = opts.out_dir;

    for group in m.all_groups_mut() {
        if !include_dev {
            group.retain(|item| !item.dev);
        }

        // Items naming a single `.lua` file need a second entry for its bytecode;
        // items naming a directory pick it up on their own.
        let compiled: Vec<ContentItem> = group
            .iter()
            .filter_map(|item| {
                let path = item.path.compiled_path()?;
                if !out_dir.join(path.as_str()).exists() {
                    return None;
                }
                let dest = match &item.dest {
                    Some(d) => match d.compiled_path() {
                        Some(c) => Some(c),
                        None => {
                            log::warn!(
                                "no bytecode destination for {:?}, shipping sources only",
                                item.name
                            );
                            return None;
                        }
                    },
                    None => None,
                };
                Some(ContentItem {
                    name: format!("{} (compiled)", item.name),
                    path,
                    dest,
                    depends: item.depends.clone(),
                    exclude: Vec::new(),
                    dev: item.dev,
                })
            })
            .collect();

        group.extend(compiled);
    }

    m
}

fn write_manifest(m: &Manifest, out_dir: &Path) -> Result<(), PackageError> {
    let path = out_dir.join(crate::manifest::FILE_NAME);
    let yaml = serde_yml::to_string(m).map_err(|e| PackageError::Io {
        context: format!("serializing {}", path.display()),
        source: std::io::Error::other(e),
    })?;
    std::fs::write(&path, yaml).map_err(|e| PackageError::Io {
        context: format!("writing {}", path.display()),
        source: e,
    })
}

/// Turn a package id into a filename: `Jurg/MyTool` -> `Jurg-MyTool`.
pub fn archive_base_name(id: &str) -> String {
    id.replace(['/', '\\'], "-")
}

/// Progress steps a build reports: one per file copied, one per script compiled.
pub fn count_steps(manifest: &Manifest, manifest_dir: &Path, include_dev: bool) -> usize {
    count_files(manifest_dir, manifest, include_dev)
        + count_lua_files(manifest_dir, manifest, include_dev)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::luac::LuacError;
    use crate::manifest;
    use std::fs;
    use tempfile::TempDir;

    /// Stand-in for the WASM compiler: prefixes the source so tests can tell
    /// bytecode from source, and can be told to fail.
    struct FakeCompiler {
        fail: bool,
        calls: Vec<String>,
    }

    impl FakeCompiler {
        fn new() -> Self {
            Self {
                fail: false,
                calls: Vec::new(),
            }
        }

        fn failing() -> Self {
            Self {
                fail: true,
                calls: Vec::new(),
            }
        }
    }

    impl LuaCompiler for FakeCompiler {
        fn compile(&mut self, source: &[u8]) -> Result<Vec<u8>, LuacError> {
            self.calls.push(String::from_utf8_lossy(source).to_string());
            if self.fail {
                return Err(LuacError::Compile {
                    message: "input:1: syntax error near 'oops'".into(),
                });
            }
            let mut out = b"\x1bLuaS".to_vec();
            out.extend_from_slice(source);
            Ok(out)
        }
    }

    /// Create a source package: `edgetx.yml` plus each (path, contents) file.
    fn source_package(yml: &str, files: &[(&str, &str)]) -> TempDir {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join(manifest::FILE_NAME), yml).unwrap();
        for (path, contents) in files {
            let p = dir.path().join(path);
            fs::create_dir_all(p.parent().unwrap()).unwrap();
            fs::write(&p, contents).unwrap();
        }
        dir
    }

    const TOOL_YML: &str = r#"
package:
  id: github.com/Jurg/MyTool
  name: My Tool
  description: A test tool
tools:
  - name: MyTool
    path: SCRIPTS/TOOLS/MyTool
"#;

    fn build(
        src: &TempDir,
        out: &TempDir,
        layout: BuildLayout,
        compiler: &mut dyn LuaCompiler,
    ) -> Result<BuildResult, PackageError> {
        let m = manifest::load(src.path()).unwrap();
        build_package(
            &BuildOptions {
                manifest: &m,
                manifest_dir: src.path(),
                out_dir: out.path(),
                include_dev: false,
                layout,
            },
            compiler,
            &mut |_| {},
            &mut |_| {},
        )
    }

    #[test]
    fn package_layout_compiles_next_to_sources() {
        let src = source_package(
            TOOL_YML,
            &[
                ("SCRIPTS/TOOLS/MyTool/main.lua", "return 1"),
                ("SCRIPTS/TOOLS/MyTool/lib.lua", "return 2"),
                ("SCRIPTS/TOOLS/MyTool/icon.png", "png"),
            ],
        );
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::new();
        let result = build(&src, &out, BuildLayout::Package, &mut compiler).unwrap();

        assert_eq!(result.scripts_compiled, 2);
        for name in ["main.lua", "main.luac", "lib.lua", "lib.luac", "icon.png"] {
            assert!(
                out.path().join("SCRIPTS/TOOLS/MyTool").join(name).exists(),
                "{name} missing from the build"
            );
        }
        assert_eq!(
            fs::read(out.path().join("SCRIPTS/TOOLS/MyTool/main.luac")).unwrap(),
            b"\x1bLuaSreturn 1"
        );
    }

    #[test]
    fn package_layout_emits_installable_manifest() {
        let src = source_package(TOOL_YML, &[("SCRIPTS/TOOLS/MyTool/main.lua", "return 1")]);
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::new();
        let result = build(&src, &out, BuildLayout::Package, &mut compiler).unwrap();

        let emitted = result.manifest.unwrap();
        assert!(emitted.package.binary, "bytecode must survive the install");
        assert!(emitted.package.source_dir.0.is_empty());

        // The output directory loads and validates as a package of its own.
        let reloaded = manifest::load(out.path()).unwrap();
        reloaded.validate(out.path()).unwrap();
        assert_eq!(reloaded.package.id, "github.com/Jurg/MyTool");
    }

    #[test]
    fn package_layout_drops_dev_items() {
        let yml = r#"
package:
  id: github.com/Jurg/MyTool
  description: A test tool
tools:
  - name: MyTool
    path: SCRIPTS/TOOLS/MyTool
  - name: Fixtures
    path: SCRIPTS/TOOLS/Fixtures
    dev: true
"#;
        let src = source_package(
            yml,
            &[
                ("SCRIPTS/TOOLS/MyTool/main.lua", "return 1"),
                ("SCRIPTS/TOOLS/Fixtures/fake.lua", "return 2"),
            ],
        );
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::new();
        let result = build(&src, &out, BuildLayout::Package, &mut compiler).unwrap();

        assert!(!out.path().join("SCRIPTS/TOOLS/Fixtures").exists());
        assert_eq!(result.manifest.unwrap().tools.len(), 1);
        // The dev script must not have been compiled either.
        assert_eq!(compiler.calls, vec!["return 1"]);
    }

    #[test]
    fn single_file_items_get_a_bytecode_entry() {
        let yml = r#"
package:
  id: github.com/Jurg/MyTool
  description: A test tool
functions:
  - name: Logger
    path: SCRIPTS/FUNCTIONS/logger.lua
"#;
        let src = source_package(yml, &[("SCRIPTS/FUNCTIONS/logger.lua", "return 1")]);
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::new();
        let result = build(&src, &out, BuildLayout::Package, &mut compiler).unwrap();

        let emitted = result.manifest.unwrap();
        let paths: Vec<&str> = emitted.functions.iter().map(|i| i.path.as_str()).collect();
        assert_eq!(
            paths,
            vec![
                "SCRIPTS/FUNCTIONS/logger.lua",
                "SCRIPTS/FUNCTIONS/logger.luac"
            ],
            "the generated bytecode needs its own entry or the install would drop it"
        );
    }

    #[test]
    fn stale_bytecode_is_replaced() {
        let src = source_package(
            TOOL_YML,
            &[
                ("SCRIPTS/TOOLS/MyTool/main.lua", "return 1"),
                ("SCRIPTS/TOOLS/MyTool/main.luac", "stale bytecode"),
            ],
        );
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::new();
        build(&src, &out, BuildLayout::Package, &mut compiler).unwrap();

        assert_eq!(
            fs::read(out.path().join("SCRIPTS/TOOLS/MyTool/main.luac")).unwrap(),
            b"\x1bLuaSreturn 1",
            "a stale .luac in the sources must not reach the build"
        );
    }

    #[test]
    fn bundled_bytecode_is_kept() {
        let yml = r#"
package:
  id: github.com/Jurg/MyTool
  description: A test tool
  binary: true
tools:
  - name: MyTool
    path: SCRIPTS/TOOLS/MyTool
"#;
        let src = source_package(
            yml,
            &[
                ("SCRIPTS/TOOLS/MyTool/main.lua", "return 1"),
                ("SCRIPTS/TOOLS/MyTool/main.luac", "shipped bytecode"),
            ],
        );
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::new();
        let result = build(&src, &out, BuildLayout::Package, &mut compiler).unwrap();

        assert_eq!(result.scripts_compiled, 0);
        assert!(compiler.calls.is_empty());
        assert_eq!(
            fs::read(out.path().join("SCRIPTS/TOOLS/MyTool/main.luac")).unwrap(),
            b"shipped bytecode"
        );
    }

    #[test]
    fn bytecode_matches_the_source_timestamp() {
        let src = source_package(TOOL_YML, &[("SCRIPTS/TOOLS/MyTool/main.lua", "return 1")]);
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::new();
        build(&src, &out, BuildLayout::Package, &mut compiler).unwrap();

        let dir = out.path().join("SCRIPTS/TOOLS/MyTool");
        let lua = fs::metadata(dir.join("main.lua"))
            .unwrap()
            .modified()
            .unwrap();
        let luac = fs::metadata(dir.join("main.luac"))
            .unwrap()
            .modified()
            .unwrap();
        assert_eq!(lua, luac);
    }

    #[test]
    fn compile_errors_name_the_script() {
        let src = source_package(TOOL_YML, &[("SCRIPTS/TOOLS/MyTool/main.lua", "return 1")]);
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::failing();
        let err = build(&src, &out, BuildLayout::Package, &mut compiler).unwrap_err();

        let msg = err.to_string();
        assert!(msg.contains("SCRIPTS/TOOLS/MyTool/main.lua"), "got {msg}");
        assert!(msg.contains("syntax error"), "got {msg}");
    }

    #[test]
    fn sd_overlay_layout_uses_install_destinations() {
        let yml = r#"
package:
  id: github.com/Jurg/MyTool
  description: A test tool
tools:
  - name: MyTool
    path: src/MyTool
    dest: SCRIPTS/TOOLS/MyTool
"#;
        let src = source_package(yml, &[("src/MyTool/main.lua", "return 1")]);
        let out = TempDir::new().unwrap();

        let mut compiler = FakeCompiler::new();
        let result = build(&src, &out, BuildLayout::SdOverlay, &mut compiler).unwrap();

        assert!(out.path().join("SCRIPTS/TOOLS/MyTool/main.lua").exists());
        assert!(out.path().join("SCRIPTS/TOOLS/MyTool/main.luac").exists());
        assert!(!out.path().join("src").exists(), "sources must be remapped");
        assert!(
            !out.path().join(manifest::FILE_NAME).exists(),
            "an SD overlay carries no manifest"
        );
        assert!(result.manifest.is_none());
    }

    #[test]
    fn archive_base_name_is_filename_safe() {
        assert_eq!(archive_base_name("Jurg/MyTool"), "Jurg-MyTool");
        assert_eq!(
            archive_base_name("github.com/Jurg/MyTool"),
            "github.com-Jurg-MyTool"
        );
        assert_eq!(archive_base_name("MyTool"), "MyTool");
    }
}
